// Package status computes which tasks of a workspace are answered, which
// answers are in effect, and the order in which they form the workspace's
// book. It works on loaded trees and never touches git.
package status

import (
	"maps"
	"slices"

	"github.com/emeland-io/custos/internal/catalog"
	"github.com/emeland-io/custos/internal/task"
	"github.com/emeland-io/custos/internal/workspace"
)

// State tells whether a task needs work.
type State string

const (
	Unanswered    State = "unanswered"
	Answered      State = "answered"       // answer exists for the current version
	PendingUpdate State = "pending-update" // only answers for older versions, or answers of merged tasks, are in effect
)

// TaskStatus is the state of one current task, from the catalog or
// generated by a processor.
type TaskStatus struct {
	ID         string
	Current    task.Ref // current version
	Title      string
	AnswerType task.AnswerType
	Generated  bool
	State      State
	Answer     *workspace.Answer   // this task's own answer file, any version; nil if none
	Merged     []*workspace.Answer // answers of tasks merged into this one (superseded tasks), for reference, always listed
	InEffect   []*workspace.Answer // what the book shows: own answer at the current version; otherwise own older answer plus the Merged answers it does not cover
}

// Entry is one line of the book, in order.
type Entry struct {
	Depth int            // 0 = top-level group
	Group *catalog.Group // heading entry when non-nil
	Task  *TaskStatus    // task entry when non-nil
}

// Status is the state of a workspace at one commit.
type Status struct {
	Workspace string
	Pin       string        // catalog commit
	Tasks     []*TaskStatus // book order
	Book      []Entry
}

// Compute derives the status of workspace w from the catalog c at its pin.
// The trees are expected to be valid; for invalid ones it does its best and
// never panics: tasks without a single current version are left out.
func Compute(w *workspace.Workspace, c *catalog.Catalog) *Status {
	b := &builder{
		w: w, c: c,
		byID:       map[string]*TaskStatus{},
		mergedInto: map[string]string{},
		children:   map[string][]string{},
		placed:     map[string]bool{},
		groupSeen:  map[string]bool{},
	}
	for _, id := range c.Tasks.Tasks() {
		if cur, ok := c.Tasks.Current(id); ok {
			b.add(c.Tasks, cur, false)
		}
	}
	var generated []string
	for _, id := range w.Graph.Tasks() {
		if cur, ok := w.Graph.Current(id); ok && !c.Tasks.Has(id) {
			b.add(w.Graph, cur, true)
			generated = append(generated, id)
		}
	}
	for _, id := range generated {
		parent := b.parent(id)
		if into, ok := b.mergedInto[parent]; ok {
			parent = into
		}
		b.children[parent] = append(b.children[parent], id)
	}
	b.layout(generated)
	return &Status{Workspace: w.Config.Workspace, Pin: w.Config.Catalog.Commit, Tasks: b.tasks, Book: b.book}
}

type builder struct {
	w          *workspace.Workspace
	c          *catalog.Catalog
	byID       map[string]*TaskStatus
	mergedInto map[string]string   // superseded task → current task that merged it
	children   map[string][]string // task → generated tasks shown below it
	placed     map[string]bool
	groupSeen  map[string]bool
	tasks      []*TaskStatus
	book       []Entry
}

// add records the status of the task whose current version is cur in graph g.
func (b *builder) add(g *task.Graph, cur *task.Version, generated bool) {
	ts := &TaskStatus{
		ID: cur.ID, Current: cur.Ref(), Title: cur.Title, AnswerType: cur.AnswerType,
		Generated: generated, Answer: b.answer(cur.ID),
	}
	for _, id := range slices.Sorted(maps.Keys(reach(g, cur))) {
		if id == cur.ID || !g.Superseded(id) {
			continue
		}
		b.mergedInto[id] = cur.ID
		if a := b.answer(id); a != nil {
			ts.Merged = append(ts.Merged, a)
		}
	}
	switch {
	case ts.Answer != nil && ts.Answer.TaskVersion == cur.Version:
		ts.State = Answered
		ts.InEffect = []*workspace.Answer{ts.Answer}
	case ts.Answer != nil || len(ts.Merged) > 0:
		ts.State = PendingUpdate
		covered := map[string]bool{}
		if ts.Answer != nil {
			ts.InEffect = append(ts.InEffect, ts.Answer)
			if v, ok := g.Lookup(task.Ref{ID: cur.ID, Version: ts.Answer.TaskVersion}); ok {
				covered = reach(g, v)
			}
		}
		for _, a := range ts.Merged {
			if !covered[a.Task] {
				ts.InEffect = append(ts.InEffect, a)
			}
		}
	default:
		ts.State = Unanswered
	}
	b.byID[cur.ID] = ts
}

// answer returns the answer file of task id, if any.
func (b *builder) answer(id string) *workspace.Answer {
	if a := b.w.Answers["answers/"+id+".md"]; a != nil && a.Task == id {
		return a
	}
	return nil
}

// parent returns the task a generated task is shown below: its origin, or
// else the task whose answer produced it.
func (b *builder) parent(id string) string {
	cur, _ := b.w.Graph.Current(id)
	g := b.w.Generated[cur.Path]
	if g == nil {
		return ""
	}
	if g.Origin != nil && g.Origin.ID != "" {
		return g.Origin.ID
	}
	return g.ProducedBy.Task.ID
}

// layout builds the book: the groups depth-first from groups/index.yaml,
// then the tasks no group lists under Ungrouped, catalog tasks first.
func (b *builder) layout(generated []string) {
	for _, slug := range b.c.Index {
		b.group(slug, 0)
	}
	heading := len(b.book)
	b.book = append(b.book, Entry{Depth: 0, Group: &catalog.Group{Slug: "", Title: "Ungrouped"}})
	for _, id := range b.c.Tasks.Tasks() {
		if b.byID[id] != nil && !b.placed[id] {
			b.task(id, 1)
		}
	}
	for _, id := range generated { // parent unknown, or a cycle of origins
		if !b.placed[id] {
			b.task(id, 1)
		}
	}
	if len(b.book) == heading+1 {
		b.book = b.book[:heading]
	}
}

func (b *builder) group(slug string, depth int) {
	g := b.c.Groups[slug]
	if g == nil || b.groupSeen[slug] {
		return
	}
	b.groupSeen[slug] = true
	b.book = append(b.book, Entry{Depth: depth, Group: g})
	for _, ch := range g.Children {
		switch {
		case ch.Group != "":
			b.group(ch.Group, depth+1)
		case b.byID[ch.Task] != nil && !b.placed[ch.Task]:
			b.task(ch.Task, depth+1)
		}
	}
}

func (b *builder) task(id string, depth int) {
	ts := b.byID[id]
	b.placed[id] = true
	b.book = append(b.book, Entry{Depth: depth, Task: ts})
	b.tasks = append(b.tasks, ts)
	for _, child := range b.children[id] {
		if !b.placed[child] {
			b.task(child, depth+1)
		}
	}
}

// reach returns the ids of the tasks whose versions v lists as previous,
// directly or indirectly, and v's own task.
func reach(g *task.Graph, v *task.Version) map[string]bool {
	ids := map[string]bool{}
	seen := map[task.Ref]bool{}
	stack := []*task.Version{v}
	for len(stack) > 0 {
		cur := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		if seen[cur.Ref()] {
			continue
		}
		seen[cur.Ref()] = true
		ids[cur.ID] = true
		for _, p := range cur.Previous {
			if pv, ok := g.Lookup(p); ok {
				stack = append(stack, pv)
			}
		}
	}
	return ids
}
