// Package task defines task versions and the rules that apply to them,
// whether they come from the catalog or were generated by a processor.
package task

import (
	"slices"
	"strings"

	"github.com/google/uuid"

	"github.com/emeland-io/custos/internal/frontmatter"
	"github.com/emeland-io/custos/internal/problem"
	"github.com/emeland-io/custos/internal/semver"
)

// AnswerType is the kind of answer a task asks for.
type AnswerType string

const (
	AnswerMarkdown  AnswerType = "markdown"
	AnswerText      AnswerType = "text"
	AnswerTimestamp AnswerType = "timestamp"
	AnswerPath      AnswerType = "path"
	AnswerURL       AnswerType = "url"
	AnswerChoice    AnswerType = "choice"
)

var answerTypes = []AnswerType{AnswerMarkdown, AnswerText, AnswerTimestamp, AnswerPath, AnswerURL, AnswerChoice}

// Valid reports whether t is one of the known answer types.
func (t AnswerType) Valid() bool { return slices.Contains(answerTypes, t) }

func answerTypeList() string {
	names := make([]string, len(answerTypes))
	for i, t := range answerTypes {
		names[i] = string(t)
	}
	return strings.Join(names, ", ")
}

// Ref names one version of one task.
type Ref struct {
	ID      string `yaml:"id" json:"id"`
	Version string `yaml:"version" json:"version"`
}

func (r Ref) String() string { return r.ID + "@" + r.Version }

// Meta is the frontmatter of a task version file.
type Meta struct {
	ID         string     `yaml:"id"`
	Version    string     `yaml:"version"`
	Title      string     `yaml:"title"`
	AnswerType AnswerType `yaml:"answer_type"`
	Choices    []string   `yaml:"choices,omitempty"`
	Previous   []Ref      `yaml:"previous,omitempty"`
}

// Ref returns the reference to this version.
func (m Meta) Ref() Ref { return Ref{ID: m.ID, Version: m.Version} }

// Version is one task version file.
type Version struct {
	Meta
	Body string // task description in Markdown
	Path string // path of the file in its repository
}

// ValidID reports whether s is a canonical lowercase UUID v4.
func ValidID(s string) bool {
	u, err := uuid.Parse(s)
	return err == nil && u.String() == s && u.Version() == 4 && u.Variant() == uuid.RFC4122
}

// ParseFile decodes a catalog task version file stored at path. It returns
// nil when the file cannot be decoded at all.
func ParseFile(path string, data []byte) (*Version, []problem.Problem) {
	var m Meta
	body, err := frontmatter.Decode(data, &m)
	if err != nil {
		return nil, []problem.Problem{{Path: path, Rule: problem.RuleFormat, Message: err.Error()}}
	}
	return &Version{Meta: m, Body: body, Path: path}, CheckMeta(m, path, "tasks")
}

// CheckMeta checks the fields of a task version stored at path below dir
// ("tasks" in a catalog, "generated" in a workspace). References to other
// versions are checked by Graph.Check.
func CheckMeta(m Meta, path, dir string) []problem.Problem {
	var ps problem.List
	if !ValidID(m.ID) {
		ps.Add(path, problem.RuleFormat, "id %q is not a lowercase UUID v4", m.ID)
	}
	if !semver.Valid(m.Version) {
		ps.Add(path, problem.RuleFormat, "version %q is not a semantic version such as 1.2.0", m.Version)
	}
	if want := dir + "/" + m.ID + "/" + m.Version + ".md"; path != want {
		ps.Add(path, problem.RulePath, "file must be stored as %s", want)
	}
	if strings.TrimSpace(m.Title) == "" {
		ps.Add(path, problem.RuleFormat, "title is missing")
	}
	if !m.AnswerType.Valid() {
		ps.Add(path, problem.RuleFormat, "answer_type %q is not one of %s", m.AnswerType, answerTypeList())
	}
	if m.AnswerType == AnswerChoice {
		if len(m.Choices) == 0 {
			ps.Add(path, problem.RuleFormat, "answer_type choice needs a non-empty choices list")
		}
		seen := map[string]bool{}
		for _, c := range m.Choices {
			if strings.TrimSpace(c) == "" {
				ps.Add(path, problem.RuleFormat, "choices must not be empty")
			}
			if seen[c] {
				ps.Add(path, problem.RuleFormat, "duplicate choice %q", c)
			}
			seen[c] = true
		}
	} else if len(m.Choices) > 0 {
		ps.Add(path, problem.RuleFormat, "choices are only allowed with answer_type choice")
	}
	seen := map[Ref]bool{}
	for _, r := range m.Previous {
		switch {
		case !ValidID(r.ID) || !semver.Valid(r.Version):
			ps.Add(path, problem.RulePrevious, "previous entry %s is not a valid id and version", r)
		case r == m.Ref():
			ps.Add(path, problem.RulePrevious, "previous must not list the version itself")
		case seen[r]:
			ps.Add(path, problem.RulePrevious, "previous lists %s twice", r)
		}
		seen[r] = true
	}
	return ps
}
